---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icesihealth-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icesihealth-backend
  template:
    metadata:
      labels:
        app: icesihealth-backend
    spec:
      containers:
      - name: icesihealth-backend
        image: camilaleniss/icesihealth-backend
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8089 # As is defined in the Javascript app
---
apiVersion: v1
kind: Service
metadata:
  name: icesihealth-backend
  labels:
    app: icesihealth-backend
spec:
  ports:
  - port: 8089
    targetPort: 8089
  selector:
    app: icesihealth-backend
